name: Template Cleanup
on:
  push:
    branches: [main]

jobs:

  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'dotnet-template'
    permissions:
      contents: write
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          export LC_CTYPE=C
          export LANG=C

          # Prepare variables
          NAME="${GITHUB_REPOSITORY##*/}"
          ACTOR=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')
          SAFE_NAME=$(echo $NAME | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          SAFE_ACTOR=$(echo $ACTOR | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          GROUP="com.github.$SAFE_ACTOR.$SAFE_NAME"

          # Replace placeholders in the template-cleanup files
          sed -i "s/%NAME%/$NAME/g" .github/template-cleanup/*
          sed -i "s/%REPOSITORY%/${GITHUB_REPOSITORY/\//\\/}/g" .github/template-cleanup/*
          sed -i "s/%GROUP%/$GROUP/g" .github/template-cleanup/*

          # Replace template package name in project files with $GROUP
          find src -type f -exec sed -i "s/com.github.kjs.template/$GROUP/g" {} +
          find src -type f -exec sed -i "s/kotlin-js-template/$NAME/g" {} +

          # Replace with some of the root files
          for file in build.gradle.kts settings.gradle.kts; do
            sed -i "s/com.github.kjs.template/$GROUP/g" "$file"
            sed -i "s/kotlin-js-template/$NAME/g" "$file"
          done

          # Move content
          mkdir -p src/jsMain/kotlin/${GROUP//.//}
          mkdir -p src/jsTest/kotlin/${GROUP//.//}
          cp -R .github/template-cleanup/. .
          cp -R src/jsMain/kotlin/com/github/kjs/template/* src/jsMain/kotlin/${GROUP//.//}/
          cp -R src/jsTest/kotlin/com/github/kjs/template/* src/jsTest/kotlin/${GROUP//.//}/

          # Cleanup
          rm -rf \
            .github/readme \
            .github/template-cleanup \
            .github/workflows/template-cleanup.yml \
            src/jsMain/kotlin/com/github/kjs/template \
            src/jsTest/kotlin/com/github/kjs/template \
            LICENSE

      # Commit modified files
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}